version: 0.0
os: linux
files:
  - source: /
    destination: /server/deploy
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runsas: ec2-user
